server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /scan.sh {
        try_files $uri =404;
        add_header Content-Type text/plain;
        add_header Content-Disposition 'attachment; filename="scan.sh"';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
